import { Router, type IRouter } from "express";
import healthRouter from "./health";
import carsRouter from "./cars";
import sellersRouter from "./sellers";
import sellerProfileRouter from "./seller-profile";
import sellerDashboardRouter from "./seller-dashboard";
import inspectorDashboardRouter from "./inspector-dashboard";
import buyerDashboardRouter from "./buyer-dashboard";
import statsRouter from "./stats";
import authRouter from "./auth";
import newsRouter from "./news";
import supportRouter from "./support";
import walletRouter from "./wallet";
import messagesRouter from "./messages";
import listingsRouter from "./listings";
import offersRouter from "./offers";
import storageRouter from "./storage";
import paystackRouter from "./paystack";
import adminRouter from "./admin";
import notificationsRouter from "./notifications";
import adsRouter from "./ads";
import appReviewsRouter from "./app-reviews";
import seoRouter from "./seo";
import onboardingRouter from "./onboarding";

const router: IRouter = Router();

router.use(healthRouter);
router.use(seoRouter);
router.use(authRouter);
router.use(carsRouter);
router.use(sellerProfileRouter);
router.use(sellerDashboardRouter);
router.use(inspectorDashboardRouter);
router.use(buyerDashboardRouter);
router.use(sellersRouter);
router.use(statsRouter);
router.use(newsRouter);
router.use(supportRouter);
router.use(walletRouter);
router.use(messagesRouter);
router.use(listingsRouter);
router.use(offersRouter);
router.use(storageRouter);
router.use(paystackRouter);
router.use(adminRouter);
router.use(notificationsRouter);
router.use(adsRouter);
router.use(appReviewsRouter);
router.use(onboardingRouter);

export default router;
